// Code generated by protoc-gen-go-micro. DO NOT EDIT.
// versions:
// - protoc-gen-go-micro v3.10.4
// - protoc              v3.21.12
// source: test.proto

package testpb

import (
	context "context"
	client "go.unistack.org/micro/v4/client"
)

var (
	TestServiceName = "TestService"
)

type TestServiceClient interface {
	Call(ctx context.Context, req *CallReq, opts ...client.CallOption) (*CallRsp, error)
}

type TestServiceServer interface {
	Call(ctx context.Context, req *CallReq, rsp *CallRsp) error
}
